In [1]:
import numpy as np
np.random.seed(0)

x1 = np.random.randint(10, size= 6)
x2 = np.random.randint(10, size = (3,4))
x3 = np.random.randint(10, size = (3,4,5))

In [2]:
print(x1)

[5 0 3 3 7 9]


In [3]:
print("x3 ndim: ", x3.ndim)
print("x3 shape :", x3.shape)
print("x3 size :", x3.size)

x3 ndim:  3
x3 shape : (3, 4, 5)
x3 size : 60


In [4]:
print("dtype :", x3.dtype)

dtype : int32


In [5]:
print("itmesize :", x3.itemsize, "bytes")
print("nbytes : ", x3.nbytes, "bytes" )

itmesize : 4 bytes
nbytes :  240 bytes


In [6]:
x1

array([5, 0, 3, 3, 7, 9])

In [7]:
x2[0,0]

3

In [8]:
x1[0,0]
x1[0,0] = 3.12323
x1[0,0]

IndexError: too many indices for array

In [9]:
x2[0,0]
x2[0,0] = 3.2434
x2[0,0]

3

In [10]:
x = np.arrange(10)

AttributeError: module 'numpy' has no attribute 'arrange'

In [11]:
x = np.arange(10)

In [12]:
x[::2]
x[1::2]

array([1, 3, 5, 7, 9])

In [13]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
x[::2]

array([0, 2, 4, 6, 8])

In [15]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [16]:
x[5::-2]

array([5, 3, 1])

In [17]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [18]:
x2[:2, :3]

array([[3, 5, 2],
       [7, 6, 8]])

In [19]:
x2[::-1, ::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

In [20]:
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [21]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[3 5]
 [7 6]]


In [22]:
x2_sub[0,0]= 99
print(x2_sub)
print(x)

[[99  5]
 [ 7  6]]
[0 1 2 3 4 5 6 7 8 9]


In [23]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [24]:
x2_sub_copy = x2[:2,:2].copy()
print(x2_sub_copy)
x2_sub_copy[0,0] = 300
print(x2)

[[99  5]
 [ 7  6]]
[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [25]:
grid = np.arange(1,10).reshpae((3,3))
print(grid)

AttributeError: 'numpy.ndarray' object has no attribute 'reshpae'

In [26]:
grid = np.arange(1,10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
x = np.array([1,2,3])
x.reshape((1,3))
print(x)

[1 2 3]


In [28]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [29]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [30]:
print(x)

[1 2 3]


In [31]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [32]:
x = np.array([1,2,3])
y = np.array([3,2,1])

np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [1]:
z = [99,99,99]
print(np.concatenate([x,y,z]))

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [3]:
x = np.array([1,2,3])
y = np.array([3,2,1])
z = [9,9,9]
print(np.concatenate([x,y,z]))

[1 2 3 3 2 1 9 9 9]


In [4]:
print(type(np.concatenate([x,y,z])))

<class 'numpy.ndarray'>


In [5]:
grid= np.array([1,2,3], [4,5,6])
np.concatenate([grid, grid])

TypeError: data type not understood

In [6]:
gird = np.array([[1,2,3], [4,5,6]])
np.concatenate([grid, gird])

NameError: name 'grid' is not defined

In [7]:
np.concatenate([gird, gird])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [8]:
np.concatenate([gird,gird], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [9]:
x = np.array([1,2,3])
grid = np.array([[9,8,7], [6,5,4]])
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [10]:
y = np.hstack([x, gird])

ValueError: all the input arrays must have same number of dimensions

In [11]:
y = np.array([99], [99])
np.hstack([grid, y])

TypeError: data type not understood

In [12]:
y = np.array([[99], [99]])
np.hstakc([grid, y])

AttributeError: module 'numpy' has no attribute 'hstakc'

In [13]:
np.hstack([grid,y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [14]:
x = [1,2,3,99,3,2,1]
x1,x2,x3 = np.split(x, [3,5])
print(x1,x2,x3)

[1 2 3] [99  3] [2 1]


In [15]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [16]:
upper, lower = np.vsplit(grid, [2])

In [17]:
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [18]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [19]:
gird = [[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]

In [20]:
np.dsplit(grid,[2])

ValueError: dsplit only works on arrays of 3 or more dimensions

In [21]:
grid = np.arange(27).reshape(3,3,3)
grid

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [22]:
np.dsplit(grid, [2])

[array([[[ 0,  1],
         [ 3,  4],
         [ 6,  7]],
 
        [[ 9, 10],
         [12, 13],
         [15, 16]],
 
        [[18, 19],
         [21, 22],
         [24, 25]]]), array([[[ 2],
         [ 5],
         [ 8]],
 
        [[11],
         [14],
         [17]],
 
        [[20],
         [23],
         [26]]])]

In [23]:
np.dsplit(grid, [2], axis = 1)

TypeError: dsplit() got an unexpected keyword argument 'axis'

In [24]:
x=np.arange(9).reshape((3,3))

In [25]:
2**x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

In [26]:
theat = linspace(0,np.pi,3)

NameError: name 'linspace' is not defined

In [27]:
theta = np.linspace(0,np.pi,3)

In [28]:
np.sin(theta)
np.cos(theta)
np.tan(theta)

array([ 0.00000000e+00,  1.63312394e+16, -1.22464680e-16])

In [29]:
theta

array([0.        , 1.57079633, 3.14159265])

In [30]:
np.sin(theta)

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [31]:
np.cos(theta)

array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

In [32]:
np.tan(theta)

array([ 0.00000000e+00,  1.63312394e+16, -1.22464680e-16])

In [33]:
np.sin(theta)
np.cos(theta)
np.tan(theta)

array([ 0.00000000e+00,  1.63312394e+16, -1.22464680e-16])

In [34]:
x = [1,2,3]
power(x,3)

NameError: name 'power' is not defined

In [35]:
print(np.exp(x))
print(np.exp2(x))
print(np.power(x,3))

[ 2.71828183  7.3890561  20.08553692]
[2. 4. 8.]
[ 1  8 27]


In [36]:
print(np.expm1(x))
print(np.log1p(x))

[ 1.71828183  6.3890561  19.08553692]
[0.69314718 1.09861229 1.38629436]
